/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomSlidesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  theme: "default",
  hideNavigateLeft: true,
  hideNavigateRight: true,
  hideNavigateUp: true,
  hideNavigateDown: true,
  hideCloseBtn: true,
  progressHeight: 10,
  leftAlignBullets: false,
  respectObsidianSettings: true,
  enablePan: true,
  enableZoom: true,
  enableWASD: false,
  transition: "slide-horizontal",
  footerText: "",
  showSlideNumbers: false,
  slideNumberPosition: "bottom-left",
  enableAutoFit: true
};
function getPlatformDefaults() {
  if (import_obsidian.Platform.isMobile) {
    return {
      hideNavigateLeft: false,
      hideNavigateRight: false,
      hideNavigateUp: false,
      hideNavigateDown: false,
      hideCloseBtn: false
    };
  }
  return {};
}

// src/ui/settings-tab.ts
var import_obsidian2 = require("obsidian");
var CustomSlidesSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.icon = "lucide-monitor-cog";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const generalGroup = new import_obsidian2.SettingGroup(containerEl);
    generalGroup.addSetting((setting) => {
      setting.setName("Theme").setDesc("Choose a reveal.js theme for your presentations.").addDropdown((dropdown) => dropdown.addOptions({
        "default": "Default (match Obsidian)",
        "black": "Black",
        "white": "White",
        "league": "League",
        "beige": "Beige",
        "night": "Night",
        "serif": "Serif",
        "simple": "Simple",
        "solarized": "Solarized",
        "moon": "Moon",
        "dracula": "Dracula",
        "sky": "Sky",
        "blood": "Blood"
      }).setValue(this.plugin.settings.theme).onChange(async (value) => {
        this.plugin.settings.theme = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Transition effect").setDesc("Choose a transition effect between slides.").addDropdown((dropdown) => dropdown.addOptions({
        "slide-horizontal": "Slide horizontal (default)",
        "slide-vertical": "Slide vertical",
        "fade": "Fade",
        "none": "None (instant)"
      }).setValue(this.plugin.settings.transition).onChange(async (value) => {
        this.plugin.settings.transition = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Use WASD for navigation").setDesc("Use W, A, S, D keys to navigate slides. Q jumps to first slide, E to last.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableWASD).onChange(async (value) => {
        this.plugin.settings.enableWASD = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Hide left navigation arrow").setDesc("Toggle visibility of the left navigation arrow.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideNavigateLeft).onChange(async (value) => {
        this.plugin.settings.hideNavigateLeft = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Hide right navigation arrow").setDesc("Toggle visibility of the right navigation arrow.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideNavigateRight).onChange(async (value) => {
        this.plugin.settings.hideNavigateRight = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Hide up navigation arrow").setDesc("Toggle visibility of the up navigation arrow.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideNavigateUp).onChange(async (value) => {
        this.plugin.settings.hideNavigateUp = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Hide down navigation arrow").setDesc("Toggle visibility of the down navigation arrow.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideNavigateDown).onChange(async (value) => {
        this.plugin.settings.hideNavigateDown = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Hide close button").setDesc("Toggle visibility of the close button.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideCloseBtn).onChange(async (value) => {
        this.plugin.settings.hideCloseBtn = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Left-align lists").setDesc("Toggle to left-align bulleted and numbered lists in presentation mode.").addToggle((toggle) => toggle.setValue(this.plugin.settings.leftAlignBullets).onChange(async (value) => {
        this.plugin.settings.leftAlignBullets = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Progress bar height").setDesc("Set the height of the progress bar in pixels.").addText((text) => text.setPlaceholder("Enter height in pixels").setValue(this.plugin.settings.progressHeight.toString()).onChange(async (value) => {
        const numValue = parseInt(value, 10);
        if (!isNaN(numValue) && numValue >= 0) {
          this.plugin.settings.progressHeight = numValue;
          await this.plugin.saveSettings();
        }
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Use Obsidian font settings").setDesc("Use the same font as your Obsidian text settings in slides.").addToggle((toggle) => toggle.setValue(this.plugin.settings.respectObsidianSettings).onChange(async (value) => {
        this.plugin.settings.respectObsidianSettings = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Enable pan").setDesc("Allow clicking and dragging to move slides around.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enablePan).onChange(async (value) => {
        this.plugin.settings.enablePan = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Enable zoom").setDesc("Allow using the mouse wheel to zoom in and out of slides.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableZoom).onChange(async (value) => {
        this.plugin.settings.enableZoom = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Footer text").setDesc("Text displayed at the bottom of every slide except the title slide. Leave empty for no footer.").addText((text) => text.setPlaceholder("Confidential").setValue(this.plugin.settings.footerText).onChange(async (value) => {
        this.plugin.settings.footerText = value;
        await this.plugin.saveSettings();
      }));
    });
    generalGroup.addSetting((setting) => {
      setting.setName("Show slide numbers").setDesc("Display a slide number on each slide, excluding the title slide.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showSlideNumbers).onChange(async (value) => {
        this.plugin.settings.showSlideNumbers = value;
        await this.plugin.saveSettings();
        this.display();
      }));
    });
    if (this.plugin.settings.showSlideNumbers) {
      generalGroup.addSetting((setting) => {
        setting.setName("Slide number position").setDesc("Choose where the slide number appears.").addDropdown((dropdown) => dropdown.addOptions({
          "bottom-left": "Bottom left",
          "bottom-right": "Bottom right"
        }).setValue(this.plugin.settings.slideNumberPosition).onChange(async (value) => {
          this.plugin.settings.slideNumberPosition = value;
          await this.plugin.saveSettings();
        }));
      });
    }
    generalGroup.addSetting((setting) => {
      setting.setName("Auto-fit slides").setDesc("Automatically shrink overflowing slide content to fit the viewport.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAutoFit).onChange(async (value) => {
        this.plugin.settings.enableAutoFit = value;
        await this.plugin.saveSettings();
      }));
    });
  }
};

// src/utils/mode-observer.ts
var import_obsidian3 = require("obsidian");
var ModeObserver = class {
  constructor(plugin) {
    this.previousMode = null;
    this.isInSlidesMode = false;
    this.observer = null;
    this.plugin = plugin;
  }
  setup() {
    this.observer = new MutationObserver((mutations, obs) => {
      this.checkSlidesMode();
    });
    this.observer.observe(document.body, { childList: true, subtree: true });
    this.plugin.register(() => {
      var _a;
      return (_a = this.observer) == null ? void 0 : _a.disconnect();
    });
    this.checkSlidesMode();
    this.plugin.registerInterval(window.setInterval(() => {
      this.checkSlidesMode();
    }, 1e3));
  }
  checkSlidesMode() {
    var _a, _b;
    try {
      const reveal = document.querySelector(".reveal");
      if (reveal && !this.isInSlidesMode) {
        const revealDocument = reveal.ownerDocument;
        const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (activeView && activeView.containerEl.ownerDocument === revealDocument) {
          const leaf = activeView.leaf;
          const viewState = leaf.getViewState();
          this.previousMode = (_b = (_a = viewState.state) == null ? void 0 : _a.mode) != null ? _b : null;
          this.plugin.app.workspace.setActiveLeaf(leaf, { focus: true });
          void leaf.setViewState({
            type: "markdown",
            state: { mode: "preview" }
          });
          this.isInSlidesMode = true;
          this.plugin.onEnterSlidesMode();
        }
      } else if (!reveal && this.isInSlidesMode) {
        const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (activeView) {
          const leaf = activeView.leaf;
          this.plugin.app.workspace.setActiveLeaf(leaf);
          void leaf.setViewState({
            type: "markdown",
            state: { mode: this.previousMode || "source" }
          }).then(() => {
            this.isInSlidesMode = false;
            this.plugin.onExitSlidesMode();
          });
        }
      }
    } catch (e) {
    }
  }
};

// src/utils/slide-manipulator.ts
var SlideManipulator = class {
  constructor(plugin) {
    this.revealContainer = null;
    this.slidesElement = null;
    this.scale = 1;
    this.translateX = 0;
    this.translateY = 0;
    this.isPanning = false;
    this.lastMouseX = 0;
    this.lastMouseY = 0;
    this.handleSlideChanged = () => {
      this.reset();
      this.refreshSlidesElement();
      this.fitSlideToViewport();
    };
    this.handleContextMenu = (e) => {
      if (!this.plugin.settings.enablePan && !this.plugin.settings.enableZoom) return;
      e.preventDefault();
      this.reset();
    };
    this.handleWheel = (e) => {
      if (!this.plugin.settings.enableZoom || !this.slidesElement) return;
      e.preventDefault();
      const delta = -e.deltaY;
      const zoomFactor = Math.pow(1.1, delta / 100);
      const newScale = Math.min(Math.max(0.1, this.scale * zoomFactor), 10);
      if (newScale !== this.scale) {
        const rect = this.slidesElement.getBoundingClientRect();
        const centerX = rect.left + rect.width / 2;
        const centerY = rect.top + rect.height / 2;
        const mouseFromCenterX = e.clientX - centerX;
        const mouseFromCenterY = e.clientY - centerY;
        const contentX = mouseFromCenterX / this.scale;
        const contentY = mouseFromCenterY / this.scale;
        const oldScale = this.scale;
        this.scale = newScale;
        this.translateX += contentX * (oldScale - newScale);
        this.translateY += contentY * (oldScale - newScale);
        this.applyTransform();
      }
    };
    this.handleMouseDown = (e) => {
      if (!this.plugin.settings.enablePan || e.button !== 0) return;
      this.isPanning = true;
      this.lastMouseX = e.clientX;
      this.lastMouseY = e.clientY;
      document.body.classList.add("is-panning");
      e.preventDefault();
    };
    this.handleMouseMove = (e) => {
      if (document.activeElement instanceof HTMLIFrameElement) {
        window.focus();
      }
      if (!this.isPanning || !this.slidesElement) return;
      const deltaX = e.clientX - this.lastMouseX;
      const deltaY = e.clientY - this.lastMouseY;
      this.translateX += deltaX;
      this.translateY += deltaY;
      this.lastMouseX = e.clientX;
      this.lastMouseY = e.clientY;
      this.applyTransform();
    };
    this.handleMouseUp = () => {
      this.isPanning = false;
      document.body.classList.remove("is-panning");
    };
    this.reset = () => {
      this.scale = 1;
      this.translateX = 0;
      this.translateY = 0;
      this.isPanning = false;
      if (this.slidesElement) {
        this.slidesElement.style.translate = "";
        this.slidesElement.style.scale = "";
        this.slidesElement.style.transformOrigin = "";
      }
      document.body.classList.remove("is-panning");
    };
    this.plugin = plugin;
  }
  setup() {
    this.attachListeners();
  }
  attachListeners() {
    const reveal = document.querySelector(".reveal");
    if (!reveal) return;
    this.revealContainer = reveal;
    this.refreshSlidesElement();
    this.revealContainer.addEventListener("wheel", this.handleWheel, { passive: false });
    this.revealContainer.addEventListener("mousedown", this.handleMouseDown);
    this.revealContainer.addEventListener("contextmenu", this.handleContextMenu);
    window.addEventListener("mousemove", this.handleMouseMove);
    window.addEventListener("mouseup", this.handleMouseUp);
    this.revealContainer.addEventListener("slidechanged", this.handleSlideChanged);
    this.revealContainer.addEventListener("ready", this.handleSlideChanged);
    this.refreshSlidesElement();
  }
  refreshSlidesElement() {
    var _a;
    if (!this.revealContainer) return;
    this.slidesElement = this.revealContainer.querySelector(".slides > section.present");
    if (!this.slidesElement) {
      this.slidesElement = this.revealContainer.querySelector(".slides > section");
    }
    const verticalSlide = (_a = this.slidesElement) == null ? void 0 : _a.querySelector("section.present");
    if (verticalSlide) {
      this.slidesElement = verticalSlide;
    }
  }
  destroy() {
    if (this.revealContainer) {
      this.revealContainer.removeEventListener("wheel", this.handleWheel);
      this.revealContainer.removeEventListener("mousedown", this.handleMouseDown);
      this.revealContainer.removeEventListener("contextmenu", this.handleContextMenu);
      this.revealContainer.removeEventListener("slidechanged", this.handleSlideChanged);
      this.revealContainer.removeEventListener("ready", this.reset);
    }
    window.removeEventListener("mousemove", this.handleMouseMove);
    window.removeEventListener("mouseup", this.handleMouseUp);
    this.reset();
    this.revealContainer = null;
    this.slidesElement = null;
  }
  applyTransform() {
    if (!this.slidesElement) return;
    this.slidesElement.style.transformOrigin = "center center";
    this.slidesElement.style.translate = `${this.translateX}px ${this.translateY}px`;
    this.slidesElement.style.scale = `${this.scale}`;
  }
  /**
   * Auto-fit the current slide to the viewport using CSS zoom.
   *
   * CSS sets min-height: 100% on sections so they fill the .slides container.
   * If content exceeds the container height, the section grows beyond it.
   * This function detects that overflow and applies CSS zoom to shrink the
   * section back to fit. CSS zoom (unlike transform: scale) affects layout,
   * so the slide background shrinks with the content.
   *
   * Called once on slide change. User can zoom/pan freely after.
   */
  fitSlideToViewport() {
    if (!this.plugin.settings.enableAutoFit) return;
    if (!this.slidesElement) return;
    const targetSlide = this.slidesElement;
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        if (this.slidesElement === targetSlide) {
          this.applyAutoFitZoom();
        }
      });
    });
    const images = targetSlide.querySelectorAll("img");
    images.forEach((img) => {
      if (!img.complete) {
        img.addEventListener("load", () => {
          if (this.slidesElement === targetSlide) {
            this.applyAutoFitZoom();
          }
        }, { once: true });
      }
    });
  }
  applyAutoFitZoom() {
    if (!this.slidesElement) return;
    const section = this.slidesElement;
    section.style.zoom = "";
    const slidesContainer = section.closest(".slides");
    if (!slidesContainer) return;
    const containerH = slidesContainer.clientHeight;
    const naturalH = section.scrollHeight;
    if (naturalH > containerH) {
      const zoomFactor = containerH / naturalH;
      section.style.zoom = `${zoomFactor}`;
      requestAnimationFrame(() => {
        if (!this.slidesElement || !slidesContainer) return;
        const sectionRect = this.slidesElement.getBoundingClientRect();
        const containerRect = slidesContainer.getBoundingClientRect();
        if (sectionRect.height > containerRect.height + 1) {
          const correction = containerRect.height / sectionRect.height;
          const currentZoom = parseFloat(this.slidesElement.style.zoom) || 1;
          this.slidesElement.style.zoom = `${currentZoom * correction * correction}`;
        }
      });
    }
  }
};

// src/main.ts
var CustomSlidesPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.footerEl = null;
    this.slideNumberEl = null;
    this._footerVisibilityHandler = null;
    this._slideNumberHandler = null;
    this.handleWASD = (e) => {
      if (!this.settings.enableWASD) return;
      const key = e.key.toLowerCase();
      let arrowKey = "";
      let isJump = false;
      switch (key) {
        case "w":
          arrowKey = "ArrowUp";
          break;
        case "a":
          arrowKey = "ArrowLeft";
          break;
        case "s":
          arrowKey = "ArrowDown";
          break;
        case "d":
          arrowKey = "ArrowRight";
          break;
        case "q":
          isJump = true;
          break;
        // Jump to first slide
        case "e":
          isJump = true;
          break;
        // Jump to last slide
        default:
          return;
      }
      e.stopPropagation();
      e.preventDefault();
      if (isJump) {
        const jumpKey = key === "q" ? "Home" : "End";
        const event2 = new KeyboardEvent("keydown", {
          key: jumpKey,
          code: jumpKey,
          keyCode: jumpKey === "Home" ? 36 : 35,
          which: jumpKey === "Home" ? 36 : 35,
          bubbles: true,
          cancelable: true
        });
        document.dispatchEvent(event2);
        return;
      }
      const event = new KeyboardEvent("keydown", {
        key: arrowKey,
        code: arrowKey,
        keyCode: arrowKey === "ArrowLeft" ? 37 : arrowKey === "ArrowUp" ? 38 : arrowKey === "ArrowRight" ? 39 : 40,
        which: arrowKey === "ArrowLeft" ? 37 : arrowKey === "ArrowUp" ? 38 : arrowKey === "ArrowRight" ? 39 : 40,
        bubbles: true,
        cancelable: true
      });
      document.dispatchEvent(event);
    };
  }
  async onload() {
    try {
      await this.loadSettings();
      this.slideManipulator = new SlideManipulator(this);
      this.app.workspace.onLayoutReady(() => {
        this.applyDynamicStyles();
      });
      this.setupModeObserver();
      this.addSettingsTab();
    } catch (e) {
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    const platformDefaults = data === null ? getPlatformDefaults() : {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, platformDefaults, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyDynamicStyles();
    this.createSlideNumber();
  }
  applyDynamicStyles() {
    const body = document.body;
    const themeClasses = [
      "slides-theme-black",
      "slides-theme-white",
      "slides-theme-league",
      "slides-theme-beige",
      "slides-theme-night",
      "slides-theme-serif",
      "slides-theme-simple",
      "slides-theme-solarized",
      "slides-theme-moon",
      "slides-theme-dracula",
      "slides-theme-sky",
      "slides-theme-blood"
    ];
    themeClasses.forEach((cls) => body.classList.remove(cls));
    if (this.settings.theme !== "default") {
      body.classList.add(`slides-theme-${this.settings.theme}`);
    }
    const transitionClasses = [
      "slides-transition-none",
      "slides-transition-fade",
      "slides-transition-slide-horizontal",
      "slides-transition-slide-vertical"
    ];
    transitionClasses.forEach((cls) => body.classList.remove(cls));
    body.classList.add(`slides-transition-${this.settings.transition}`);
    body.classList.toggle("hide-navigate-left", this.settings.hideNavigateLeft);
    body.classList.toggle("hide-navigate-right", this.settings.hideNavigateRight);
    body.classList.toggle("hide-navigate-up", this.settings.hideNavigateUp);
    body.classList.toggle("hide-navigate-down", this.settings.hideNavigateDown);
    body.classList.toggle("hide-close-btn", this.settings.hideCloseBtn);
    body.classList.toggle("left-align-bullets", this.settings.leftAlignBullets);
    body.classList.toggle("enable-pan", this.settings.enablePan);
    body.classList.toggle("enable-zoom", this.settings.enableZoom);
    body.style.setProperty("--progress-height", `${this.settings.progressHeight}px`);
    this.applyFontStyles();
  }
  applyFontStyles() {
    const body = document.body;
    if (this.settings.respectObsidianSettings) {
      body.style.setProperty("--slides-font-interface", "var(--font-interface)");
      body.style.setProperty("--slides-font-text", "var(--font-text)");
    } else {
      body.style.removeProperty("--slides-font-interface");
      body.style.removeProperty("--slides-font-text");
    }
  }
  createFooter() {
    if (!this.settings.footerText.trim()) {
      this.footerEl = null;
      return;
    }
    const reveal = document.querySelector(".reveal");
    if (!reveal) return;
    const footer = document.createElement("div");
    footer.className = "custom-slides-footer";
    footer.textContent = this.settings.footerText;
    reveal.appendChild(footer);
    this.footerEl = footer;
    this._footerVisibilityHandler = () => this.updateFooterVisibility();
    reveal.addEventListener("slidechanged", this._footerVisibilityHandler);
    reveal.addEventListener("ready", this._footerVisibilityHandler);
    this.updateFooterVisibility();
  }
  updateFooterVisibility() {
    if (!this.footerEl) return;
    const slidesContainer = document.querySelector(".reveal .slides");
    if (!slidesContainer) return;
    const leafSlides = Array.from(slidesContainer.querySelectorAll("section")).filter((s) => s.querySelectorAll("section").length === 0);
    const currentSlide = leafSlides.find((s) => s.classList.contains("present"));
    this.footerEl.style.display = currentSlide === leafSlides[0] ? "none" : "";
  }
  destroyFooter() {
    if (this.footerEl) {
      this.footerEl.remove();
      this.footerEl = null;
    }
    if (this._footerVisibilityHandler) {
      const reveal = document.querySelector(".reveal");
      if (reveal) {
        reveal.removeEventListener("slidechanged", this._footerVisibilityHandler);
        reveal.removeEventListener("ready", this._footerVisibilityHandler);
      }
      this._footerVisibilityHandler = null;
    }
  }
  createSlideNumber() {
    this.destroySlideNumber();
    if (!this.settings.showSlideNumbers) return;
    const reveal = document.querySelector(".reveal");
    if (!reveal) return;
    const numEl = document.createElement("div");
    numEl.className = "custom-slide-number";
    numEl.classList.add(`slide-number-${this.settings.slideNumberPosition}`);
    reveal.appendChild(numEl);
    this.slideNumberEl = numEl;
    this._slideNumberHandler = () => this.updateSlideNumberVisibility();
    reveal.addEventListener("slidechanged", this._slideNumberHandler);
    reveal.addEventListener("ready", this._slideNumberHandler);
    this.updateSlideNumberVisibility();
  }
  updateSlideNumberVisibility() {
    if (!this.slideNumberEl) return;
    const slidesContainer = document.querySelector(".reveal .slides");
    if (!slidesContainer) return;
    const leafSlides = Array.from(slidesContainer.querySelectorAll("section")).filter((s) => s.querySelectorAll("section").length === 0);
    const currentSlide = leafSlides.find((s) => s.classList.contains("present"));
    if (!currentSlide || currentSlide === leafSlides[0]) {
      this.slideNumberEl.style.display = "none";
    } else {
      const index = leafSlides.indexOf(currentSlide);
      this.slideNumberEl.style.display = "";
      this.slideNumberEl.textContent = String(index);
    }
  }
  destroySlideNumber() {
    if (this.slideNumberEl) {
      this.slideNumberEl.remove();
      this.slideNumberEl = null;
    }
    if (this._slideNumberHandler) {
      const reveal = document.querySelector(".reveal");
      if (reveal) {
        reveal.removeEventListener("slidechanged", this._slideNumberHandler);
        reveal.removeEventListener("ready", this._slideNumberHandler);
      }
      this._slideNumberHandler = null;
    }
    document.querySelectorAll(".custom-slide-number").forEach((el) => el.remove());
  }
  setupModeObserver() {
    this.modeObserver = new ModeObserver(this);
    this.modeObserver.setup();
  }
  addSettingsTab() {
    this.addSettingTab(new CustomSlidesSettingTab(this.app, this));
  }
  onEnterSlidesMode() {
    this.slideManipulator.setup();
    if (this.settings.enableWASD) {
      window.addEventListener("keydown", this.handleWASD, true);
    }
    this.createFooter();
    this.createSlideNumber();
  }
  onExitSlidesMode() {
    this.slideManipulator.destroy();
    window.removeEventListener("keydown", this.handleWASD, true);
    this.destroyFooter();
    this.destroySlideNumber();
  }
  onunload() {
    this.destroySlideNumber();
    this.destroyFooter();
    const body = document.body;
    body.classList.remove(
      "slides-theme-black",
      "slides-theme-white",
      "slides-theme-league",
      "slides-theme-beige",
      "slides-theme-night",
      "slides-theme-serif",
      "slides-theme-simple",
      "slides-theme-solarized",
      "slides-theme-moon",
      "slides-theme-dracula",
      "slides-theme-sky",
      "slides-theme-blood",
      "slides-transition-none",
      "slides-transition-fade",
      "slides-transition-slide-horizontal",
      "slides-transition-slide-vertical",
      "hide-navigate-left",
      "hide-navigate-right",
      "hide-navigate-up",
      "hide-navigate-down",
      "hide-close-btn",
      "left-align-bullets",
      "enable-pan",
      "enable-zoom",
      "is-panning"
    );
    body.style.removeProperty("--progress-height");
    body.style.removeProperty("--slides-font-interface");
    body.style.removeProperty("--slides-font-text");
  }
};


/* nosourcemap */